### ISSUE TITLE
General TODO

### ISSUE THREAD

**Issue by CremBluRay** [CremBluRay/voodoo#8]
# TODO:
- [ ] Fog
- [ ] Normal Mapping of textures
- [ ] Shadows
- [ ] Animations (for models)
- [ ] Particles
- [ ] Audio #6 **Good first issue. See [LWJGL Wiki](https://github.com/LWJGL/lwjgl3-wiki/wiki/2.1.-OpenAL)**
- [ ] Instanced rendering for lots of instances of gameObjects
- [ ] 3D Object Picking (being able to select gameObjects within the scene)
- [ ] HUD revamp
- [ ] Physics
